// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFile(arg1) {
  return window['go']['bridge']['App']['CheckFile'](arg1);
}

export function CheckForUpdates(arg1) {
  return window['go']['bridge']['App']['CheckForUpdates'](arg1);
}

export function ExpandPaths(arg1) {
  return window['go']['bridge']['App']['ExpandPaths'](arg1);
}

export function GetAppVersion() {
  return window['go']['bridge']['App']['GetAppVersion']();
}

export function GetFileMetadata(arg1) {
  return window['go']['bridge']['App']['GetFileMetadata'](arg1);
}

export function InstallUpdate(arg1) {
  return window['go']['bridge']['App']['InstallUpdate'](arg1);
}

export function OptimizeFile(arg1) {
  return window['go']['bridge']['App']['OptimizeFile'](arg1);
}

export function SelectDirectory() {
  return window['go']['bridge']['App']['SelectDirectory']();
}

export function SelectFiles() {
  return window['go']['bridge']['App']['SelectFiles']();
}
