// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {analyzer} from '../models';

export function CheckFile(arg1:string):Promise<boolean>;

export function CheckForUpdates(arg1:string):Promise<updater.CheckResult>;

export function ExpandPaths(arg1:Array<string>):Promise<Array<string>>;

export function GetAppVersion():Promise<string>;

export function GetFileMetadata(arg1:string):Promise<analyzer.Metadata>;

export function InstallUpdate(arg1:string):Promise<void>;

export function OptimizeFile(arg1:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectFiles():Promise<Array<string>>;
